# Generated by Django 3.0.9 on 2020-08-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200618_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='document',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
